config/routes.rb
Rails.application.routes.draw do
  root 'habits#previewer'
  get '/', to: 'habits#previewer', as: 'previewer'
  patch '/move/habit/:id', to: 'habits#move'
  get '/habits/edit', to: 'habits#edit', as: 'edit_habits'
  get '/profile', to: 'dashboard#current_user_profile', as: 'profile'
  get 'reports', to: 'habits#habit_reports', as: 'habit_reports'
  post '/habits', to: 'habits#create', as: 'create_habit'
  post '/habit/:id', to: 'habits#log_habit', as: 'log_habit'
  delete '/habit/:id', to: 'habits#delete_habit', as: 'delete_habit'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_bottom_navbar.html.erb
<% if user_signed_in? %>
   <div data-controller='new-habit-form'>
     <div class="w-full fixed bottom-0 py-8 px-4 flex items-center justify-center">
       <div class="flex text-sm items-center justify-center gap-10 w-[90%] px-4 h-10 rounded-full bg-zinc-900 text-white relative">
         <%= link_to "Reports", habit_reports_path, data: {turbo_frame: "habit_list", turbo_action: "advance"} %>
         <div class="z-10 p-2 rounded-full bg-zinc-900 w-max border border-gray-500 shadow-lg drop-shadow-xl cursor-pointer" data-new-habit-form-target="newHabitBtn" data-action="click->new-habit-form#openForm">
           <%= render partial: 'shared/icons/add', locals: {className: 'fill-white h-9 w-auto'} %>
         </div>
         <%= link_to "Edit", edit_habits_path, data: {turbo_frame: "home_previewer", turbo_action: 'advance'} %>
       </div>
     </div>
     <div data-new-habit-form-target="bgOverlay" class="z-20 fixed inset-0 bg-gray-300 bg-opacity-75 flex items-end hidden" data-action="click->new-habit-form#closeForm">
       <div class="w-full rounded-t-[1.5rem] h-[50%] bg-white shadow-xl p-4 open-form" data-new-habit-form-target="popUpForm" >
         <div class="w-full">
           <%= form_with url: create_habit_path, model: Habit.new, method: :post, data: {new_habit_form_target: 'form', action: 'turbo:submit-start->new-habit-form#reset'} do |f| %>
             <%= f.text_field :name, class: 'text-lg w-full border-none outline-none border-transparent focus:border-transparent focus:ring-0 font-medium', placeholder: 'Habit name' %>
             <%= f.text_area :description, class: 'w-full border-none outline-none border-transparent focus:border-transparent focus:ring-0 font-medium', placeholder: 'Description' %>
             <div class="flex w-full gap-2">
               <%= f.number_field :frequency, placeholder: 'Frequency', class: 'rounded-xl border-gray-200' %>
               <%= f.select :habit_type, [['Daily', 'daily'], ['Weekly', 'weekly'], ['Monthly', 'monthly']], {}, {class: 'border-gray-200 outline-none focus:ring-0 rounded-xl'} %>
             </div>
             <%= f.hidden_field :user_id, value: current_user.id %>
             <button type="submit" class="p-2 rounded-full bg-zinc-900 w-max shadow-lg drop-shadow-xl cursor-pointer fixed bottom-8 right-8" data-new-habit-form-target="submitBtn">
               <%= render partial: 'shared/icons/arrow_up', locals: {className: 'fill-white'} %>
             </button>
           <% end %>
         </div>

       </div>
     </div>
   </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="flex w-full justify-between p-4 items-center">
    <h3 class="text-sm"><%= Time.now.strftime('%d %B') %></h3>
    <%= link_to profile_path do %>
      <%= render partial: 'shared/icons/user', locals: {className: ''} %>
    <% end %>
  </div>
  <div class="w-full flex justify-end items-center px-4">
    <div class="flex rounded-full p-1 border border-slate-300 text-xs gap-1 w-max" data-controller="previewer">
      <% ['daily', 'weekly', 'monthly'].each_with_index do |val, idx| %>
        <%= link_to val.capitalize, "?view=#{val}", class: "p-2 rounded-full hover:bg-gray-200", data: {previewer_target: val, action: "previewer#changeIndex", previewer_index_param: idx, turbo_frame: 'home_previewer', turbo_action: 'advance'}  %>
      <% end %>
    </div>
  </div>
<% end %>