config/routes.rb
Rails.application.routes.draw do
  root 'habits#previewer'
  get '/', to: 'habits#previewer', as: 'previewer'
  patch '/move/habit/:id', to: 'habits#move'
  get '/habits/edit', to: 'habits#edit', as: 'edit_habits'
  get '/profile', to: 'dashboard#current_user_profile', as: 'profile'
  get 'reports', to: 'habits#habit_reports', as: 'habit_reports'
  post '/habits', to: 'habits#create', as: 'create_habit'
  post '/habit/:id', to: 'habits#log_habit', as: 'log_habit'
  delete '/habit/:id', to: 'habits#delete_habit', as: 'delete_habit'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/habit.rb
class Habit < ApplicationRecord
  belongs_to :user
  acts_as_list scope: :user
  validates :name, presence: true, length: { maximum: 100 }
  validates :description, length: { maximum: 500 }
  validates :habit_type, inclusion: { in: %w[daily weekly monthly], message: '%<value>s is not a valid type' }
  validates :frequency, numericality: { only_integer: true }
  has_many :habit_logs, dependent: :destroy

  # GET how many is accomplished today
  def logs_for_today
    habit_logs.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
  end

  def current_logs
    if habit_type == 'daily'
      logs_for_today
    elsif habit_type == 'weekly'
      logs_for_this_week
    else
      logs_for_this_month
    end
  end

  # GET how many is accomplished this week
  def logs_for_this_week
    date = Time.now
    week_number = date.day > 28 ? 4 : (date.day / 7.0).ceil
    range = get_week_range(week_number)
    habit_logs.where(created_at: range, habit_id: id)
  end

  # GET how many is accomplished this month
  def logs_for_this_month
    habit_logs.where(created_at: Time.now.beginning_of_month..Time.now.end_of_month)
  end

  private

  def get_week_range(week_number)
    date = Time.now
    case week_number
    when 1
      Time.new(date.year, date.month, 1)..Time.new(date.year, date.month, 7)
    when 2
      Time.new(date.year, date.month, 8)..Time.new(date.year, date.month, 14)
    when 3
      Time.new(date.year, date.month, 15)..Time.new(date.year, date.month, 21)
    when 4
      Time.new(date.year, date.month, 22)..Time.new(date.year, date.month, date.end_of_month.day)
    end
  end
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :authenticate_user!
  before_action :instantiate_data, only: %i[habit_reports previewer]

  def index; end

  def edit
    @habits = current_user.habits
  end

  def previewer; end

  def new
    @habit = Habit.new
  end

  def delete_habit
    @habit = Habit.destroy(params[:id])

    respond_to(&:turbo_stream)
  end

  def create
    @habit = Habit.new(new_habits_params)

    respond_to do |format|
      # looks for a turbo_stream template
      #
      # located at: views/habits/create.turbo_stream.erb
      format.turbo_stream if @habit.save
    end
  end

  def move
    @habit = Habit.find(params[:id])
    @habit.insert_at(params[:position].to_i)
    head :ok
  end

  def log_habit
    @habit = Habit.find_by(id: params[:id])
    @habit_log = HabitLog.new(user_id: @habit.user_id, habit_id: @habit.id)
    @amount = @habit.current_logs.length

    respond_to do |format|
      if @amount < @habit.frequency
        if @habit_log.save
          @amount += 1
          format.turbo_stream
        end

      else
        format.html { redirect_to previewer_path('daily') }
      end
    end
  end

  def habit_reports
    @date = params[:date] ? Time.parse(params[:date]) : Time.now
    @report_percentage = params[:percentage] || HabitLog.get_daily_report(current_user.id, @date)[:report_percentage]
  end

  private

  def instantiate_data
    @habits = Habit.where(user_id: current_user.id)
    @mode = params[:view] || 'daily'
  end

  def new_habits_params
    params.require(:habit).permit(:user_id, :name, :description, :habit_type, :frequency)
  end
end

app/helpers/habits_helper.rb
module HabitsHelper
  def get_week_number(date = Time.now)
    # The day today should be divided with 7
    #
    # "How many 7 days are there in the day today?"
    return 4 if date.day > 28

    (date.day / 7.0).ceil
  end

  def get_week_range(week_number)
    date = Time.now
    case week_number
    when 1
      Time.new(date.year, date.month, 1)..Time.new(date.year, date.month, 7)
    when 2
      Time.new(date.year, date.month, 8)..Time.new(date.year, date.month, 14)
    when 3
      Time.new(date.year, date.month, 15)..Time.new(date.year, date.month, 21)
    when 4
      Time.new(date.year, date.month, 22)..Time.new(date.year, date.month, date.end_of_month.day)
    end
  end

  def daily_reports_this_month
    date = Time.zone.now
    last_day_of_the_month = date.end_of_month.day
    results = []
    (1..last_day_of_the_month).each do |n|
      new_date = Time.new(date.year, date.month, n)
      results.push({**HabitLog.get_daily_report(current_user.id, new_date), date: new_date})
    end
    results
  end
end

app/views/habits/_habit.html.erb
<div data-id="<%= habit.id %>" id="user_<%= habit.user_id %>_habit_<%= habit.id %>" class="flex w-full items-center gap-2">
  <%= button_to log_habit_path(habit.id), data: {controller: 'authenticity habit-block', habit_block_amount_value: amount, habit_block_frequency_value: habit.frequency}, form_class: 'grow ', class: 'w-full' do %>
    <div class="p-4 w-full border border-slate-300 rounded-lg shadow-sm flex justify-between relative" data-habit-block-target="habitDiv">
      <span class="font-medium z-50 text-left"><%= habit.name %></span>
      <div class="z-50 text-right">
        <span class=""><%= amount %> / <%= habit.frequency %></span>
        <span class="">
          <% if habit.habit_type == 'daily' %>
            <%= 'today' %>
          <% elsif habit.habit_type == 'weekly' %>
            <%= 'this week' %>
          <% else %>
            <%= 'this month' %>
          <% end %>
        </span>
      </div>
    </div>
  <% end %>
</div>

app/views/habits/_previewer_header.html.erb
<section>
  <div class="flex justify-between w-full items-center previewer-load">
    <% if mode == 'daily' %>
        <h1 class="text-4xl font-bold previewer-load"><%= Time.now.strftime('%A') %></h1>
    <% elsif mode == 'weekly' %>
      <h1 class="text-4xl font-bold previewer-load">Week <%= get_week_number %></h1>
    <% else %>
      <h1 class="text-4xl font-bold previewer-load"><%= Time.now.strftime('%B') %></h1>
    <% end %>
  </div>
</section>

app/views/habits/create.turbo_stream.erb
<%= turbo_stream.append "user_#{@habit.user_id}_#{@habit.habit_type}_habits", partial: 'habit', locals: {habit: @habit, amount: @habit.current_logs.length} %>

app/views/habits/delete_habit.turbo_stream.erb
<%= turbo_stream.remove "habit_#{@habit.id}_edit" %>

app/views/habits/edit.html.erb
<main class="px-4">
  <%= turbo_frame_tag "home_previewer" do %>
    <%= link_to previewer_path, data: {turbo_action: 'advance'} do %>
      <div class="w-full flex items-center">
        <%= render partial: 'shared/icons/chevron_left', locals: {className: 'w-6 h-auto stroke-2'} %>
        <span class="text-4xl font-bold previewer-load">Back</span>
      </div>
    <% end %>
    <section class="flex flex-col gap-2 py-2">
      <% @habits.each do |habit| %>
        <div id="<%= dom_id(habit) %>_edit" class="flex items-center gap-2">
          <span><%= habit.name %></span>
          <%= button_to delete_habit_path(habit.id), method: :delete do %>
            <%= render partial: 'shared/icons/trash', locals: {className: ''} %>
          <% end %>
        </div>
      <% end %>
    </section>
  <% end %>
</main>

app/views/habits/habit_reports.html.erb
<% reports = daily_reports_this_month %>
<main class="px-4">
  <%= turbo_frame_tag "home_previewer", class: 'flex flex-col gap-2' do %>
    <%= link_to previewer_path, data: {turbo_action: 'advance'} do %>
      <div class="w-full flex items-center">
        <%= render partial: 'shared/icons/chevron_left', locals: {className: 'w-6 h-auto stroke-2'} %>
        <span class="text-4xl font-bold previewer-load">Reports</span>
      </div>
    <% end %>
    <%= turbo_frame_tag "habit_list", class: '' do %>
      <div class="previewer-load flex w-full justify-center">
        <% if @mode == 'daily' %>
          <span class="font-medium text-lg"><%= @report_percentage %>% completion, <%= @date.strftime('%d %B') %></span>
        <% elsif @mode == 'weekly' %>
          <span class="font-medium text-lg"><%= HabitLog.get_weekly_report(current_user.id, get_week_range(get_week_number))[:report_percentage] %>% completion this week</span>
        <% end %>
      </div>
      <% if @mode == 'daily' %>
        <section class="mt-10 flex flex-col gap-2">
          <div class="w-full rounded-lg flex flex-wrap gap-1">
            <% reports.each_with_index do |n, idx| %>
              <%= link_to habit_reports_path(date: n[:date], percentage: n[:report_percentage]) do %>
                <div class='relative h-9 w-9 min-w-24 rounded-xl' data-controller="report-graph" data-report-graph-percentage-value="<%= n[:report_percentage] %>">
                </div>
              <% end %>
            <% end %>
          </div>
          <div>
          </div>
        </section>
      <% end %>
    <% end %>
  <% end %>
</main>

app/views/habits/index.html.erb
<%= render 'shared/navbar' %>
<main class="px-4 w-full min-h-screen">
  <%= turbo_frame_tag "home_previewer", src: previewer_path  %>
</main>
<%= render 'new_habit' %>

app/views/habits/log_habit.turbo_stream.erb
<%= turbo_stream.replace "user_#{@habit_log.user_id}_habit_#{@habit_log.habit_id}", partial: 'habit', locals: {habit: @habit_log.habit, amount: @amount} %>

app/views/habits/new.html.erb
<main class="p-4">
</main>

app/views/habits/previewer.html.erb
<main class="px-4">
  <%= turbo_frame_tag "home_previewer", class: 'flex flex-col gap-2' do %>
    <%= render partial: 'previewer_header', locals: {mode: @mode}  %>
    <%= turbo_frame_tag "habit_list", class: 'list overflow-y-scroll' do %>
      <section id="<%= dom_id(current_user) %>_<%= @mode %>_habits" class="previewer-load flex flex-col gap-2 py-2" data-controller="drag-list">
        <% @habits.each do |item| %>
          <% if item.habit_type == @mode %>
            <%= render partial: 'habit', locals: {habit: item, amount: item.current_logs.length} %>
          <% end %>
        <% end %>
      </section>
    <% end %>
    <section class="w-full flex">
    </section>
  <% end %>
</main>